os: linux
dist: trusty
language: c
cache:
  ccache: true
  directories:
    - ~/.ccache
before_script:
  - sudo apt-get install u-boot-tools device-tree-compiler mtools
script:
  - du --block-size=M --max-depth=1 ~
  - du --block-size=M --max-depth=1 .
  - while sleep 5; do tail -n 5 build/pi_3_b/current.log; done &
  - MODEL=pi_3_b BUILD_TYPE=DEBUG make
  - kill %1
  - while sleep 5; do tail -n 5 build/pi_b_plus/current.log; done &
  - MODEL=pi_b_plus BUILD_TYPE=DEBUG make
  - kill %1
