language: c
cache:
  ccache: true
  directories:
    - ~/.buildroot-ccache
    - ~/.ccache
    - ./buildroot-2017.02.10/dl
    - ./build/pi_b_plus/buildroot
before_script:
  - sudo apt-get remove autoconf
  - sudo apt-get install u-boot-tools device-tree-compiler
script:
  - du --block-size=M --max-depth=1 ~
  - du --block-size=M --max-depth=1 .
  - while sleep 5; do tail -n 5 build/pi_b_plus/current.log; done &
  - make
  - kill %1
